-- Migration 021: additive API installation trust and asset-catalog authority.
--
-- Existing device-bound users are deliberately quarantined. This migration does
-- not interpret X-Device-ID as proof of ownership and does not transfer legacy
-- scenarios. Opaque credentials are generated by the API; PostgreSQL receives
-- and persists only a 32-byte keyed verifier and its bounded key version.

BEGIN;

DO $contract_preflight$
DECLARE
    owner_role text;
    api_cap text;
    audit_cap text;
BEGIN
    SELECT contract.owner_role,
           contract.api_capability_role,
           contract.audit_capability_role
      INTO owner_role,api_cap,audit_cap
      FROM public.saydin_role_contract contract
     WHERE contract.singleton=1
       AND contract.contract_schema_version=1
       AND contract.database_name=pg_catalog.current_database();

    IF owner_role IS NULL OR api_cap IS NULL OR audit_cap IS NULL
       OR CURRENT_USER IS DISTINCT FROM owner_role
       OR NOT EXISTS (SELECT 1 FROM pg_catalog.pg_roles WHERE rolname=owner_role)
       OR NOT EXISTS (SELECT 1 FROM pg_catalog.pg_roles WHERE rolname=api_cap)
       OR NOT EXISTS (SELECT 1 FROM pg_catalog.pg_roles WHERE rolname=audit_cap) THEN
        RAISE EXCEPTION 'API trust role contract rejected' USING ERRCODE='42501';
    END IF;
END;
$contract_preflight$;

ALTER TABLE public.users
    ADD COLUMN principal_status varchar(32) NOT NULL DEFAULT 'legacy_quarantined',
    ADD COLUMN principal_contract_version integer NOT NULL DEFAULT 1,
    ADD COLUMN principal_quarantined_at timestamptz NULL DEFAULT pg_catalog.statement_timestamp(),
    ADD COLUMN principal_revoked_at timestamptz NULL,
    ADD COLUMN principal_expires_at timestamptz NULL,
    ADD CONSTRAINT chk_users_principal_status CHECK
        (principal_status IN ('legacy_quarantined','active','revoked')),
    ADD CONSTRAINT chk_users_principal_contract_version CHECK
        (principal_contract_version>0),
    ADD CONSTRAINT chk_users_principal_lifecycle CHECK (
        (principal_status='legacy_quarantined'
            AND principal_quarantined_at IS NOT NULL
            AND principal_revoked_at IS NULL)
        OR (principal_status='active'
            AND device_id IS NULL
            AND principal_quarantined_at IS NULL
            AND principal_revoked_at IS NULL)
        OR (principal_status='revoked' AND principal_revoked_at IS NOT NULL)),
    ADD CONSTRAINT chk_users_principal_expiry CHECK
        (principal_expires_at IS NULL OR principal_expires_at>created_at);

CREATE TABLE public.installation_credentials (
    id uuid PRIMARY KEY,
    principal_id uuid NOT NULL,
    generation integer NOT NULL,
    secret_hash bytea NOT NULL,
    hash_key_version smallint NOT NULL,
    state varchar(16) NOT NULL,
    issued_at timestamptz NOT NULL DEFAULT pg_catalog.clock_timestamp(),
    pending_expires_at timestamptz NULL,
    expires_at timestamptz NULL,
    activated_at timestamptz NULL,
    revoked_at timestamptz NULL,
    rotation_parent_id uuid NULL,
    rotation_id uuid NULL,
    CONSTRAINT fk_installation_credentials_principal FOREIGN KEY(principal_id)
        REFERENCES public.users(id) ON DELETE CASCADE,
    CONSTRAINT fk_installation_credentials_rotation_parent FOREIGN KEY(rotation_parent_id)
        REFERENCES public.installation_credentials(id) ON DELETE RESTRICT,
    CONSTRAINT chk_installation_credentials_generation CHECK(generation>0),
    CONSTRAINT chk_installation_credentials_hash_key_version CHECK(hash_key_version>0),
    CONSTRAINT chk_installation_credentials_secret_hash CHECK(
        pg_catalog.octet_length(secret_hash)=32
        AND secret_hash<>pg_catalog.decode(pg_catalog.repeat('00',32),'hex')),
    CONSTRAINT chk_installation_credentials_state CHECK
        (state IN ('pending','active','revoked')),
    CONSTRAINT chk_installation_credentials_lifecycle CHECK(
        (state='pending' AND activated_at IS NULL AND revoked_at IS NULL
            AND pending_expires_at IS NOT NULL AND pending_expires_at>issued_at)
        OR (state='active' AND activated_at IS NOT NULL AND revoked_at IS NULL
            AND pending_expires_at IS NULL)
        OR (state='revoked' AND revoked_at IS NOT NULL)),
    CONSTRAINT chk_installation_credentials_expiry CHECK
        (expires_at IS NULL OR expires_at>issued_at),
    CONSTRAINT chk_installation_credentials_rotation CHECK(
        (rotation_id IS NULL AND rotation_parent_id IS NULL)
        OR (rotation_id IS NOT NULL AND rotation_parent_id IS NOT NULL)),
    CONSTRAINT uq_installation_credentials_verifier UNIQUE(hash_key_version,secret_hash),
    CONSTRAINT uq_installation_credentials_generation UNIQUE(principal_id,generation)
);

CREATE UNIQUE INDEX uq_installation_credentials_active_principal
    ON public.installation_credentials(principal_id) WHERE state='active';
CREATE UNIQUE INDEX uq_installation_credentials_pending_principal
    ON public.installation_credentials(principal_id) WHERE state='pending';
CREATE UNIQUE INDEX uq_installation_credentials_rotation_id
    ON public.installation_credentials(rotation_id) WHERE rotation_id IS NOT NULL;

CREATE TABLE public.asset_catalog_state (
    singleton smallint PRIMARY KEY,
    revision bigint NOT NULL,
    catalog_sha256 bytea NOT NULL,
    updated_at timestamptz NOT NULL DEFAULT pg_catalog.clock_timestamp(),
    CONSTRAINT chk_asset_catalog_state_singleton CHECK(singleton=1),
    CONSTRAINT chk_asset_catalog_state_revision CHECK(revision>0),
    CONSTRAINT chk_asset_catalog_state_sha256 CHECK(
        pg_catalog.octet_length(catalog_sha256)=32)
);

CREATE FUNCTION public.compute_asset_catalog_sha256()
RETURNS bytea
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path=pg_catalog,pg_temp
AS $body$
    SELECT pg_catalog.sha256(pg_catalog.convert_to(
        COALESCE(
            (SELECT pg_catalog.jsonb_agg(
                        pg_catalog.jsonb_build_object(
                            'id',asset.id::text,
                            'symbol',asset.symbol,
                            'display_name',asset.display_name,
                            'category',asset.category::text,
                            'is_active',asset.is_active,
                            'source',asset.source,
                            'source_id',asset.source_id,
                            'metadata',asset.metadata)
                        ORDER BY asset.id)::text
               FROM public.assets asset),
            '[]'),
        'UTF8'));
$body$;

INSERT INTO public.asset_catalog_state(singleton,revision,catalog_sha256)
VALUES(1,1,public.compute_asset_catalog_sha256());

CREATE FUNCTION public.refresh_asset_catalog_state()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path=pg_catalog,pg_temp
AS $body$
BEGIN
    -- Serialize catalog publication first. Under READ COMMITTED, keeping the
    -- lock acquisition and digest query as separate PL/pgSQL statements gives
    -- a waiter a fresh statement snapshot after the preceding publisher
    -- commits; otherwise an UPDATE expression can publish a stale digest even
    -- though its revision increment is protected by row-lock EPQ.
    PERFORM 1
      FROM public.asset_catalog_state state
     WHERE state.singleton=1
     FOR UPDATE;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'asset catalog singleton missing' USING ERRCODE='55000';
    END IF;

    UPDATE public.asset_catalog_state
       SET revision=revision+1,
           catalog_sha256=public.compute_asset_catalog_sha256(),
           updated_at=pg_catalog.clock_timestamp()
     WHERE singleton=1;
    RETURN NULL;
END;
$body$;

CREATE TRIGGER trg_asset_catalog_revision_insert
AFTER INSERT ON public.assets FOR EACH STATEMENT
EXECUTE FUNCTION public.refresh_asset_catalog_state();
CREATE TRIGGER trg_asset_catalog_revision_update
AFTER UPDATE ON public.assets FOR EACH STATEMENT
EXECUTE FUNCTION public.refresh_asset_catalog_state();
CREATE TRIGGER trg_asset_catalog_revision_delete
AFTER DELETE ON public.assets FOR EACH STATEMENT
EXECUTE FUNCTION public.refresh_asset_catalog_state();
CREATE TRIGGER trg_asset_catalog_revision_truncate
AFTER TRUNCATE ON public.assets FOR EACH STATEMENT
EXECUTE FUNCTION public.refresh_asset_catalog_state();

CREATE FUNCTION public.register_installation(
    p_principal_id uuid,
    p_credential_id uuid,
    p_secret_hash bytea,
    p_key_version smallint)
RETURNS TABLE(
    principal_id uuid,
    credential_id uuid,
    generation integer,
    tier varchar,
    principal_status varchar,
    credential_state varchar)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path=pg_catalog,pg_temp
AS $body$
DECLARE
    registration_time timestamptz:=pg_catalog.statement_timestamp();
BEGIN
    IF p_principal_id IS NULL OR p_credential_id IS NULL
       OR p_principal_id='00000000-0000-0000-0000-000000000000'::uuid
       OR p_credential_id='00000000-0000-0000-0000-000000000000'::uuid
       OR p_key_version IS NULL OR p_key_version<=0
       OR p_secret_hash IS NULL OR pg_catalog.octet_length(p_secret_hash)<>32
       OR p_secret_hash=pg_catalog.decode(pg_catalog.repeat('00',32),'hex') THEN
        RAISE EXCEPTION 'invalid installation registration input' USING ERRCODE='22023';
    END IF;

    INSERT INTO public.users(
        id,device_id,email,tier,principal_status,principal_contract_version,
        principal_quarantined_at,principal_revoked_at,principal_expires_at,
        created_at,last_seen_at)
    VALUES(p_principal_id,NULL,NULL,'free','active',1,NULL,NULL,NULL,
        registration_time,registration_time);

    INSERT INTO public.installation_credentials(
        id,principal_id,generation,secret_hash,hash_key_version,state,
        issued_at,pending_expires_at,expires_at,activated_at,revoked_at,
        rotation_parent_id,rotation_id)
    VALUES(p_credential_id,p_principal_id,1,p_secret_hash,p_key_version,'active',
        registration_time,NULL,NULL,registration_time,NULL,NULL,NULL);

    RETURN QUERY
    SELECT principal.id,credential.id,credential.generation,principal.tier,
           principal.principal_status,credential.state
      FROM public.users principal
      JOIN public.installation_credentials credential
        ON credential.principal_id=principal.id
     WHERE principal.id=p_principal_id AND credential.id=p_credential_id;
END;
$body$;

CREATE FUNCTION public.resolve_installation(
    p_secret_hash bytea,
    p_key_version smallint)
RETURNS TABLE(
    principal_id uuid,
    credential_id uuid,
    generation integer,
    tier varchar,
    principal_status varchar,
    credential_state varchar)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path=pg_catalog,pg_temp
AS $body$
    SELECT principal.id,credential.id,credential.generation,principal.tier,
           principal.principal_status,credential.state
      FROM public.installation_credentials credential
      JOIN public.users principal ON principal.id=credential.principal_id
     WHERE credential.hash_key_version=p_key_version
       AND credential.secret_hash=p_secret_hash
       AND pg_catalog.octet_length(p_secret_hash)=32
       AND credential.state='active'
       AND credential.activated_at<=pg_catalog.statement_timestamp()
       AND (credential.expires_at IS NULL
            OR credential.expires_at>pg_catalog.statement_timestamp())
       AND principal.principal_status='active'
       AND (principal.principal_expires_at IS NULL
            OR principal.principal_expires_at>pg_catalog.statement_timestamp());
$body$;

CREATE FUNCTION public.begin_installation_rotation(
    p_current_secret_hash bytea,
    p_current_key_version smallint,
    p_rotation_id uuid,
    p_new_credential_id uuid,
    p_new_secret_hash bytea,
    p_new_key_version smallint)
RETURNS TABLE(
    principal_id uuid,
    credential_id uuid,
    generation integer,
    tier varchar,
    principal_status varchar,
    credential_state varchar)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path=pg_catalog,pg_temp
AS $body$
DECLARE
    current_credential_id uuid;
    current_principal_id uuid;
    next_generation integer;
    rotation_started_at timestamptz:=pg_catalog.statement_timestamp();
BEGIN
    IF p_rotation_id IS NULL OR p_new_credential_id IS NULL
       OR p_rotation_id='00000000-0000-0000-0000-000000000000'::uuid
       OR p_new_credential_id='00000000-0000-0000-0000-000000000000'::uuid
       OR p_current_key_version IS NULL OR p_current_key_version<=0
       OR p_new_key_version IS NULL OR p_new_key_version<=0
       OR p_current_secret_hash IS NULL
       OR pg_catalog.octet_length(p_current_secret_hash)<>32
       OR p_new_secret_hash IS NULL OR pg_catalog.octet_length(p_new_secret_hash)<>32
       OR p_current_secret_hash=pg_catalog.decode(pg_catalog.repeat('00',32),'hex')
       OR p_new_secret_hash=pg_catalog.decode(pg_catalog.repeat('00',32),'hex') THEN
        RAISE EXCEPTION 'invalid installation rotation input' USING ERRCODE='22023';
    END IF;

    SELECT credential.id,credential.principal_id
      INTO current_credential_id,current_principal_id
      FROM public.installation_credentials credential
      JOIN public.users principal ON principal.id=credential.principal_id
     WHERE credential.hash_key_version=p_current_key_version
       AND credential.secret_hash=p_current_secret_hash
       AND credential.state='active'
       AND (credential.expires_at IS NULL OR credential.expires_at>rotation_started_at)
       AND principal.principal_status='active'
       AND (principal.principal_expires_at IS NULL OR principal.principal_expires_at>rotation_started_at);

    IF current_credential_id IS NULL THEN
        RAISE EXCEPTION 'installation authorization rejected' USING ERRCODE='28000';
    END IF;

    -- Every mutation for one principal enters the same lock domain before taking
    -- row locks. Re-read after the advisory lock so a concurrent commit/revoke
    -- cannot make the first authorization snapshot authoritative.
    PERFORM pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(
        'saydin.installation.principal:'||current_principal_id::text,0));

    SELECT credential.id,credential.principal_id
      INTO current_credential_id,current_principal_id
      FROM public.installation_credentials credential
      JOIN public.users principal ON principal.id=credential.principal_id
     WHERE credential.id=current_credential_id
       AND credential.hash_key_version=p_current_key_version
       AND credential.secret_hash=p_current_secret_hash
       AND credential.state='active'
       AND credential.activated_at<=rotation_started_at
       AND (credential.expires_at IS NULL OR credential.expires_at>rotation_started_at)
       AND principal.principal_status='active'
       AND (principal.principal_expires_at IS NULL OR principal.principal_expires_at>rotation_started_at)
     FOR UPDATE OF credential,principal;

    IF current_credential_id IS NULL THEN
        RAISE EXCEPTION 'installation authorization rejected' USING ERRCODE='28000';
    END IF;

    RETURN QUERY
    SELECT principal.id,credential.id,credential.generation,principal.tier,
           principal.principal_status,credential.state
      FROM public.installation_credentials credential
      JOIN public.users principal ON principal.id=credential.principal_id
     WHERE credential.principal_id=current_principal_id
       AND credential.id=p_new_credential_id
       AND credential.rotation_id=p_rotation_id
       AND credential.hash_key_version=p_new_key_version
       AND credential.secret_hash=p_new_secret_hash
       AND credential.state='pending'
       AND credential.pending_expires_at>rotation_started_at;
    IF FOUND THEN
        RETURN;
    END IF;

    UPDATE public.installation_credentials credential
       SET state='revoked',revoked_at=rotation_started_at
     WHERE credential.principal_id=current_principal_id
       AND credential.state='pending';

    SELECT COALESCE(MAX(credential.generation),0)+1
      INTO next_generation
      FROM public.installation_credentials credential
     WHERE credential.principal_id=current_principal_id;

    INSERT INTO public.installation_credentials(
        id,principal_id,generation,secret_hash,hash_key_version,state,
        issued_at,pending_expires_at,expires_at,activated_at,revoked_at,
        rotation_parent_id,rotation_id)
    VALUES(p_new_credential_id,current_principal_id,next_generation,
        p_new_secret_hash,p_new_key_version,'pending',rotation_started_at,
        rotation_started_at+INTERVAL '15 minutes',NULL,NULL,NULL,current_credential_id,p_rotation_id);

    RETURN QUERY
    SELECT principal.id,credential.id,credential.generation,principal.tier,
           principal.principal_status,credential.state
      FROM public.installation_credentials credential
      JOIN public.users principal ON principal.id=credential.principal_id
     WHERE credential.id=p_new_credential_id;
END;
$body$;

CREATE FUNCTION public.commit_installation_rotation(
    p_rotation_id uuid,
    p_new_secret_hash bytea,
    p_new_key_version smallint)
RETURNS TABLE(
    principal_id uuid,
    credential_id uuid,
    generation integer,
    tier varchar,
    principal_status varchar,
    credential_state varchar)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path=pg_catalog,pg_temp
AS $body$
DECLARE
    pending_credential_id uuid;
    pending_principal_id uuid;
    pending_state varchar(16);
    pending_deadline timestamptz;
    committed_at timestamptz:=pg_catalog.statement_timestamp();
BEGIN
    IF p_rotation_id IS NULL OR p_new_key_version IS NULL OR p_new_key_version<=0
       OR p_new_secret_hash IS NULL OR pg_catalog.octet_length(p_new_secret_hash)<>32
       OR p_new_secret_hash=pg_catalog.decode(pg_catalog.repeat('00',32),'hex') THEN
        RAISE EXCEPTION 'invalid installation rotation commit input' USING ERRCODE='22023';
    END IF;

    SELECT credential.id,credential.principal_id,credential.state,
           credential.pending_expires_at
      INTO pending_credential_id,pending_principal_id,pending_state,pending_deadline
      FROM public.installation_credentials credential
      JOIN public.users principal ON principal.id=credential.principal_id
     WHERE credential.rotation_id=p_rotation_id
       AND credential.hash_key_version=p_new_key_version
       AND credential.secret_hash=p_new_secret_hash
       AND credential.state IN ('pending','active')
       AND principal.principal_status='active';

    IF pending_credential_id IS NULL THEN
        RAISE EXCEPTION 'installation authorization rejected' USING ERRCODE='28000';
    END IF;

    PERFORM pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(
        'saydin.installation.principal:'||pending_principal_id::text,0));

    SELECT credential.id,credential.principal_id,credential.state,
           credential.pending_expires_at
      INTO pending_credential_id,pending_principal_id,pending_state,pending_deadline
      FROM public.installation_credentials credential
      JOIN public.users principal ON principal.id=credential.principal_id
     WHERE credential.rotation_id=p_rotation_id
       AND credential.hash_key_version=p_new_key_version
       AND credential.secret_hash=p_new_secret_hash
       AND credential.state IN ('pending','active')
       AND principal.principal_status='active'
       AND (principal.principal_expires_at IS NULL
            OR principal.principal_expires_at>committed_at)
     FOR UPDATE OF credential,principal;

    IF pending_credential_id IS NULL THEN
        RAISE EXCEPTION 'installation authorization rejected' USING ERRCODE='28000';
    END IF;

    IF pending_state='active' THEN
        RETURN QUERY
        SELECT principal.id,credential.id,credential.generation,principal.tier,
               principal.principal_status,credential.state
          FROM public.installation_credentials credential
          JOIN public.users principal ON principal.id=credential.principal_id
         WHERE credential.id=pending_credential_id;
        RETURN;
    END IF;

    IF pending_deadline IS NULL OR pending_deadline<=committed_at THEN
        RAISE EXCEPTION 'installation authorization rejected' USING ERRCODE='28000';
    END IF;

    UPDATE public.installation_credentials credential
       SET state='revoked',revoked_at=committed_at
     WHERE credential.principal_id=pending_principal_id
       AND credential.state='active';
    UPDATE public.installation_credentials credential
       SET state='active',activated_at=committed_at,pending_expires_at=NULL
     WHERE credential.id=pending_credential_id AND credential.state='pending';

    RETURN QUERY
    SELECT principal.id,credential.id,credential.generation,principal.tier,
           principal.principal_status,credential.state
      FROM public.installation_credentials credential
      JOIN public.users principal ON principal.id=credential.principal_id
     WHERE credential.id=pending_credential_id;
END;
$body$;

CREATE FUNCTION public.revoke_installation(
    p_secret_hash bytea,
    p_key_version smallint)
RETURNS TABLE(
    principal_id uuid,
    credential_id uuid,
    generation integer,
    tier varchar,
    principal_status varchar,
    credential_state varchar)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path=pg_catalog,pg_temp
AS $body$
DECLARE
    revoked_credential_id uuid;
    revoked_principal_id uuid;
    revoked_generation integer;
    revoked_tier varchar(20);
    revocation_time timestamptz:=pg_catalog.statement_timestamp();
BEGIN
    IF p_key_version IS NULL OR p_key_version<=0
       OR p_secret_hash IS NULL OR pg_catalog.octet_length(p_secret_hash)<>32
       OR p_secret_hash=pg_catalog.decode(pg_catalog.repeat('00',32),'hex') THEN
        RAISE EXCEPTION 'invalid installation revocation input' USING ERRCODE='22023';
    END IF;

    SELECT credential.id,credential.principal_id,credential.generation,principal.tier
      INTO revoked_credential_id,revoked_principal_id,revoked_generation,revoked_tier
      FROM public.installation_credentials credential
      JOIN public.users principal ON principal.id=credential.principal_id
     WHERE credential.hash_key_version=p_key_version
       AND credential.secret_hash=p_secret_hash
       AND credential.state='active'
       AND principal.principal_status='active';

    IF revoked_credential_id IS NULL THEN
        RAISE EXCEPTION 'installation authorization rejected' USING ERRCODE='28000';
    END IF;

    PERFORM pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(
        'saydin.installation.principal:'||revoked_principal_id::text,0));

    SELECT credential.id,credential.principal_id,credential.generation,principal.tier
      INTO revoked_credential_id,revoked_principal_id,revoked_generation,revoked_tier
      FROM public.installation_credentials credential
      JOIN public.users principal ON principal.id=credential.principal_id
     WHERE credential.hash_key_version=p_key_version
       AND credential.secret_hash=p_secret_hash
       AND credential.state='active'
       AND principal.principal_status='active'
     FOR UPDATE OF credential,principal;

    IF revoked_credential_id IS NULL THEN
        RAISE EXCEPTION 'installation authorization rejected' USING ERRCODE='28000';
    END IF;

    UPDATE public.installation_credentials credential
       SET state='revoked',revoked_at=revocation_time
     WHERE credential.principal_id=revoked_principal_id
       AND credential.state IN ('active','pending');
    UPDATE public.users principal
       SET principal_status='revoked',principal_revoked_at=revocation_time
     WHERE principal.id=revoked_principal_id
       AND principal.principal_status='active';

    RETURN QUERY SELECT revoked_principal_id,revoked_credential_id,
        revoked_generation,revoked_tier,'revoked'::varchar,'revoked'::varchar;
END;
$body$;

CREATE FUNCTION public.get_asset_catalog_state()
RETURNS TABLE(revision bigint,catalog_sha256 bytea,updated_at timestamptz)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path=pg_catalog,pg_temp
AS $body$
    SELECT state.revision,state.catalog_sha256,state.updated_at
      FROM public.asset_catalog_state state
     WHERE state.singleton=1;
$body$;

DO $ownership_and_acl$
DECLARE
    owner_role text;
    api_cap text;
    audit_cap text;
    function_name text;
BEGIN
    SELECT contract.owner_role,
           contract.api_capability_role,
           contract.audit_capability_role
      INTO owner_role,api_cap,audit_cap
      FROM public.saydin_role_contract contract
     WHERE contract.singleton=1
       AND contract.contract_schema_version=1
       AND contract.database_name=pg_catalog.current_database();

    IF owner_role IS NULL OR api_cap IS NULL OR audit_cap IS NULL
       OR CURRENT_USER IS DISTINCT FROM owner_role THEN
        RAISE EXCEPTION 'API trust role contract rejected' USING ERRCODE='42501';
    END IF;

    EXECUTE pg_catalog.format(
        'ALTER TABLE public.installation_credentials OWNER TO %I',owner_role);
    EXECUTE pg_catalog.format(
        'ALTER TABLE public.asset_catalog_state OWNER TO %I',owner_role);

    FOREACH function_name IN ARRAY ARRAY[
        'compute_asset_catalog_sha256()',
        'refresh_asset_catalog_state()',
        'register_installation(uuid,uuid,bytea,smallint)',
        'resolve_installation(bytea,smallint)',
        'begin_installation_rotation(bytea,smallint,uuid,uuid,bytea,smallint)',
        'commit_installation_rotation(uuid,bytea,smallint)',
        'revoke_installation(bytea,smallint)',
        'get_asset_catalog_state()']
    LOOP
        EXECUTE pg_catalog.format(
            'ALTER FUNCTION public.%s OWNER TO %I',function_name,owner_role);
        EXECUTE pg_catalog.format(
            'REVOKE ALL ON FUNCTION public.%s FROM PUBLIC',function_name);
        EXECUTE pg_catalog.format(
            'REVOKE ALL ON FUNCTION public.%s FROM %I',function_name,api_cap);
        EXECUTE pg_catalog.format(
            'REVOKE ALL ON FUNCTION public.%s FROM %I',function_name,audit_cap);
    END LOOP;

    REVOKE ALL ON TABLE public.installation_credentials,
        public.asset_catalog_state FROM PUBLIC;
    EXECUTE pg_catalog.format(
        'REVOKE ALL ON TABLE public.installation_credentials,public.asset_catalog_state FROM %I',
        api_cap);
    EXECUTE pg_catalog.format(
        'REVOKE ALL ON TABLE public.installation_credentials,public.asset_catalog_state FROM %I',
        audit_cap);

    EXECUTE pg_catalog.format(
        'GRANT EXECUTE ON FUNCTION public.register_installation(uuid,uuid,bytea,smallint),public.resolve_installation(bytea,smallint),public.begin_installation_rotation(bytea,smallint,uuid,uuid,bytea,smallint),public.commit_installation_rotation(uuid,bytea,smallint),public.revoke_installation(bytea,smallint),public.get_asset_catalog_state() TO %I',
        api_cap);
    EXECUTE pg_catalog.format(
        'GRANT SELECT ON public.asset_catalog_state TO %I',audit_cap);
END;
$ownership_and_acl$;

COMMENT ON COLUMN public.installation_credentials.secret_hash IS
    'Keyed 32-byte credential verifier; raw opaque credentials are never persisted.';
COMMENT ON TABLE public.asset_catalog_state IS
    'Authoritative singleton revision and canonical SHA-256 for every cache-affecting asset field.';
COMMENT ON FUNCTION public.begin_installation_rotation(bytea,smallint,uuid,uuid,bytea,smallint) IS
    'Creates a pending replacement while the current credential remains active; repeated identical begin is idempotent.';
COMMENT ON FUNCTION public.commit_installation_rotation(uuid,bytea,smallint) IS
    'Atomically activates a live pending replacement and revokes the previous active credential; committed retry is idempotent.';

COMMIT;
