<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>Saydin.CalendarData</AssemblyName>
    <RootNamespace>Saydin.CalendarData</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="PdfPig" />
    <PackageReference Include="Npgsql" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../../../src/Saydin.DatabaseSecurity/Saydin.DatabaseSecurity.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Saydin.CalendarData.Tests" />
  </ItemGroup>
</Project>
